INSERT INTO item_type(item_type)
VALUES
('Cloth Head'),
('Cloth Shoulders'),
('Cloth Chest'),
('Cloth Bracers'),
('Cloth Hands'),
('Cloth Belt'),
('Cloth Legs'),
('Cloth Boots'),
('Leather Head'),
('Leather Shoulders'),
('Leather Chest'),
('Leather Bracers'),
('Leather Hands'),
('Leather Belt'),
('Leather Legs'),
('Leather Boots'),
('Mail Head'),
('Mail Shoulders'),
('Mail Chest'),
('Mail Bracers'),
('Mail Hands'),
('Mail Belt'),
('Mail Legs'),
('Mail Boots'),
('Plate Head'),
('Plate Shoulders'),
('Plate Chest'),
('Plate Bracers'),
('Plate Hands'),
('Plate Belt'),
('Plate Legs'),
('Plate Boots'),
('Neck'),
('Cloak'),
('Ring'),
('Str Trinket'),
('Int Trinket'),
('Agi Trinket'),
('Agi 1H Axe'),
('Agi 1H Sword'),
('Agi 1H Dagger'),
('Agi 1H Mace'),
('Agi 1H Fist Weapon'),
('Agi 1H Warglaive'),
('Agi 2H Axe'),
('Agi 2H Sword'),
('Agi 2H Mace'),
('Agi 2H Polearm'),
('Agi 2H Gun'),
('Agi 2H Bow'),
('Agi 2H Crossbow'),
('Str 1H Axe'),
('Str 1H Sword'),
('Str 1H Mace'),
('Str Shield'),
('Str 2H Axe'),
('Str 2H Sword'),
('Str 2H Mace'),
('Str 2H Polearm'),
('Int 1H Dagger'),
('Int 1H Mace'),
('Int 1H Wand'),
('Int Shield'),
('Int Offhand'),
('Int 2H Mace'),
('Int 2H Staff'),
('Dreadful Head'),
('Dreadful Shoulders'),
('Dreadful Chest'),
('Dreadful Hands'),
('Dreadful Legs'),
('Mystic Head'),
('Mystic Shoulders'),
('Mystic Chest'),
('Mystic Hands'),
('Mystic Legs'),
('Venerated Head'),
('Venerated Shoulders'),
('Venerated Chest'),
('Venerated Hands'),
('Venerated Legs'),
('Zenith Head'),
('Zenith Shoulders'),
('Zenith Chest'),
('Zenith Hands'),
('Zenith Legs')